### ISSUE TITLE
Fatal Exception: You cannot show a dialog before an Activity is created or after it's hidden

### ISSUE THREAD

**Issue by moertel** [zixpo/candybar#103]
It has happened on the newest CandyBar version 3.16.1. I've never seen it happen before and this is a _single_ user who experienced it. However, doing a small bit of research, it seems like a legitimate glitch.

Brand: OnePlus
Model: OnePlus 6
Orientation: Portrait 
Version: Android 11
Rooted: No

```
Fatal Exception: o.t41$e: Bad window token, you cannot show a dialog before an Activity is created or after it's hidden.
       at com.afollestad.materialdialogs.MaterialDialog.show(MaterialDialog.java:466)
       at com.afollestad.materialdialogs.MaterialDialog$Builder.show(MaterialDialog.java:2189)
       at candybar.lib.helpers.LicenseCallbackHelper.showLicenseDialog(LicenseCallbackHelper.java:90)
       at candybar.lib.helpers.LicenseCallbackHelper.lambda$onLicenseCheckFinished$0(LicenseCallbackHelper.java:72)
       at candybar.lib.helpers.LicenseCallbackHelper.$r8$lambda$ejgT_oTVO_0gVEIP2rk2W7Bu10A(LicenseCallbackHelper.java)
       at candybar.lib.helpers.LicenseCallbackHelper$$InternalSyntheticLambda$3$b400bb4b38f3f8ecb1fa25cb5413fb5867117f5619d88579225385843512a5b0$0.run(LicenseCallbackHelper.java:4)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:233)
       at android.app.ActivityThread.main(ActivityThread.java:8068)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
```

I'm wondering if this would be a solution: https://stackoverflow.com/a/41118674/3405140
https://github.com/zixpo/candybar/blob/be5c7318a600a966867542fb154a07011b9a1ba3/library/src/main/java/candybar/lib/helpers/LicenseCallbackHelper.java#L54-L57
```java
if (((Activity) mContext).hasWindowFocus()) {
        mDialog.show();
}
```

**Comment by moertel** [comment]
Oh, nevermind the proposed solution, it's actually happening _here_: https://github.com/zixpo/candybar/blob/be5c7318a600a966867542fb154a07011b9a1ba3/library/src/main/java/candybar/lib/helpers/LicenseCallbackHelper.java#L90

Then I need more input on how to address it. 🤔

**Comment by sarsamurmu** [comment]
Try decreasing this timeout, I guess - https://github.com/zixpo/candybar/blob/be5c7318a600a966867542fb154a07011b9a1ba3/library/src/main/java/candybar/lib/helpers/LicenseCallbackHelper.java#L73
