### ISSUE TITLE
App crashes when changing the icon shape

### ISSUE THREAD

**Issue by bkazoo** [zixpo/candybar#82]
App crashes when changing the icon shape in the All Icons tab after choosing a new shape and choosing Close to apply.

Reproduced using CandyBar 3.14.1 and 3.14.2.

**Comment by bkazoo** [comment]
FATAL EXCEPTION: main
Process: [package name], PID: 8954
java.lang.NullPointerException: You cannot start a load on a not yet attached View or a Fragment where getActivity() returns null (which usually occurs when getActivity() is called before the Fragment is attached or after the Fragment is destroyed).
	at com.bumptech.glide.util.Preconditions.checkNotNull(Preconditions.java:29)
	at com.bumptech.glide.Glide.getRetriever(Glide.java:744)
	at com.bumptech.glide.Glide.with(Glide.java:813)
	at candybar.lib.adapters.IconsAdapter.loadIconInto(IconsAdapter.java:215)
	at candybar.lib.adapters.IconsAdapter.reloadIcons(IconsAdapter.java:228)
	at candybar.lib.fragments.IconsFragment.reloadIcons(IconsFragment.java:152)
	at candybar.lib.fragments.dialog.IconShapeChooserFragment.onDismiss(IconShapeChooserFragment.java:103)
	at androidx.fragment.app.DialogFragment$3.onDismiss(DialogFragment.java:132)
	at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1405)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:7889)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

**Comment by bkazoo** [comment]
I have been able to reproduce using candybar-sample 3.14.2 code only, in two different devices:

1. Enable Includes Adaptive Icons in _candybar-sample/app/src/main/res/values/dashboard_configurations.xml_:
`<bool name="includes_adaptive_icons">true</bool>`
2. In _candybar-sample/app/src/main/res/xml/drawable.xml_, copy the existing categories with their icons multiple times (so there are 10 categories in total).
3. Open the resulting app and browse the existing icons.
4. Move from the first to the last category.
5. Change the Icon Shape to a different one.
6. App crashes.
